services:
  coordinator:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: dl-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ../data:/app/data:ro
    command: ["./node", "-config", "/app/configs/coordinator.yaml"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  node-1:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: dl-node-1
    ports:
      - "8081:8080"
    command: ["./node", "-config", "/app/configs/node-1.yaml"]
    depends_on:
      coordinator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  node-2:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: dl-node-2
    ports:
      - "8082:8080"
    command: ["./node", "-config", "/app/configs/node-2.yaml"]
    depends_on:
      coordinator:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
